Fix undefined method 'bytesize' for nil in callback phase
v1.9.0 appears to have introduced a NoMethodError if the callback is performed without the stored state in the session